name: Build RPI ARM64 (CI)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, Linux, ARM64]

    steps:
    - uses: actions/checkout@v3
    - name: clean
      run: make cleanall
    - name: make
      run: make
    - name: Upload Build
      uses: actions/upload-artifact@v3.1.3
      with:
        name: net-nomad-hcx_aarch64
        path: /home/rage/actions-runner/_work/net-nomad-hcx/net-nomad-hcx/net-nomad-hcx_aarch64
